const ActionTypes = {
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_ERROR: 'UPLOAD_FILE_ERROR',
  SELECT_FILE: 'SELECT_FILE',

  UPDATE_COLUMN_VALUE: 'UPDATE_COLUMN_VALUE',

  GET_FORECAST_DATA: 'GET_FORECAST_DATA',
  SET_FORECAST_DATA: 'SET_FORECAST_DATA',

  GET_FILE_LIST_DATA: 'GET_FILE_LIST_DATA',
  SET_FILE_LIST_DATA: 'SET_FILE_LIST_DATA',

  GET_COLUMNS_DATA: 'GET_COLUMNS_DATA',
  SET_COLUMNS_DATA: 'SET_COLUMNS_DATA',

  GET_FILE_DATA: 'GET_FILE_DATA',
  SET_FILE_DATA: 'SET_FILE_DATA',

  DELETE_FILE: 'DELETE_FILE',
  DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
  DELETE_FILE_ERROR: 'DELETE_FILE_ERROR',

  SHOW_NOTIFICATION: 'SHOW_NOTIFICATION',
  HIDE_NOTIFICATION: 'HIDE_NOTIFICATION',

  CHANGE_DASHBOARD_TAB: 'CHANGE_DASHBOARD_TAB',
};

export default ActionTypes;
