'use strict';

const ActionTypes = {
  UPLOAD_FILE_SUCCESS: 'UPLOAD_FILE_SUCCESS',
  UPLOAD_FILE_ERROR: 'UPLOAD_FILE_ERROR',
  SET_FILE_LIST: 'SET_FILE_LIST',
  SELECT_FILE: 'SELECT_FILE',

  SET_COLUMNS: 'SET_COLUMNS',
  UPDATE_COLUMN_VALUE: 'UPDATE_COLUMN_VALUE',

  PREPARE_FORECAST_DATA: 'PREPARE_FORECAST_DATA',
};

export default ActionTypes;
